### ISSUE TITLE
LGPL licensed code in yue

### ISSUE THREAD

**Issue by drinchev** [yue/help#4]
Hello,

According to a HN user you are using large parts of WebKit source code, which is licensed with LGPL.

https://news.ycombinator.com/item?id=15220169

https://github.com/yue/yue/blob/master/nativeui/gfx/gtk/painter_gtk.cc#L90

https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/graphics/cairo/PathCairo.cpp#L206

**Comment by domino14** [comment]
A million deaths were not enough for Yue!

**Comment by magcius** [comment]
Hi, I'm the person that left the comment on Hacker News.

To give you context, the code is trying to convert from the endpoint parameterization used for elliptical arcs as used in SVG arc syntax to the more traditional center parameterization used by GDI and cairo.

You can find a specification of the algorithm used to implement this in the SVG appendix at https://www.w3.org/TR/SVG/implnote.html#ArcSyntax

Please try to implement it yourself without using WebKit's code directly.

**Comment by GnorTech** [comment]
This guy @zcbenz has a track record of copyright infringement, see https://github.com/electron/electron/issues/5172#issuecomment-210697670

**Comment by zcbenz** [comment]
I thought I could relicense the code but apparently I can't, I should have checked the license and I'm sorry for that. I'll rewrite that part of code immediately.

@magcius Thank you very much for finding out the license issue and providing the specification of the algorithm.

To give some excuse for the bad behavior, blink forked WebKit and uses BSD license, which gave me the impression that WebKit also uses BSD license, but it is still absolutely my bad not checking WebKit's license.

**Comment by magcius** [comment]
Blink uses the BSD license only for new components. Existing code is left as LGPL. There is no cairo code in Blink, since it uses Skia instead of cairo.

The [license of the Chromium project](https://chromium.googlesource.com/chromium/blink/+/master/LICENSE), in full, says:

```
// Redistribution and use in source and binary forms, with or without--
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
```

Stripping the authorship of other code is not permitted by the license.

**Comment by zcbenz** [comment]
@magcius I deleted it because we have personal issues, and it is not related to this project, I hope this deletion did not leave wrong impressions here.

And thanks a lot for auditing the licenses, I'll fix the license issues with highest priority.

**Comment by psing007** [comment]
Thief.

 " You have stripped the authorship of Chromium authors, replaced it with your own, and asserted copyright ownership over the file. "

How do you justify that  ? That is purely intentional, deceitful, and breaking the law.
Adjusting the license should be the least of your worries.

Roger Wang will hear about this.

https://groups.google.com/forum/#!topic/nwjs-general/LIrC7zHtQdo

**Comment by zcbenz** [comment]
Sorry but I have to delete another comment doing personal attacks.

**Comment by bastijnv** [comment]
I'm going put on a limb here but I'd say leaving the personal attacks and properly responding to them is going to do you more good than removing them at this point. Given the current allegations people might wonder if the removed comments are indeed personal attacks or just censorship by the project owner. Most people that find these threads are capable of discerning for themselves.

**Comment by zcbenz** [comment]
Hi, I have removed all LGPL code from Yue's codebase, and added back Chromium's license to certain source files, some APIs have been removed because of this and I'll reimplement them in future.

If you still find out code violating copyright, please let me know and I'll fix them immediately.

Again I'm very sorry I ignored copyright and it was definitely a very bad thing.
